config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# Set the main index page of the site
root 'posts#index', as: "home"

# Include paths to other views
get "about" => 'pages#about', as: "about"

# Claim a resouce of mutliple elements that share the same Controller  
resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = "About Ruby?!?!"
        @content = "This is some good content..."
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    #list of posts
    def index
        @posts = Post.all #Get all Posts
    end

    #new Post
    def new
        
    end

    #Create the new Post
    def create 
        #render plain: params[:post].inspect
        @post = Post.new(post_params) #Capture paramters from the View
        @post.save #Save the new Post object to the DV
        redirect_to @post #Display the new post once saved
    end

    #Display the new Post
    def show
        @post = Post.find(params[:id]) #Go find the latest post from the DB
    end

    private def post_params
        #Allows access to build a Post with a title and body values
        params.require(:post).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestingSite</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', home_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Post', new_post_path %>
      </li>
    </ul>
  </div>
</nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1> <!--Include items from Ruby files -->
<h1>This is the About Page</h1>
<h3><%= @content %></h3>

app/views/posts/index.html.erb
<h1>This is the Blog Posts</h1>
<% @posts.each do |post| %>
<h3><%= post.title %></h3>
<p><%= post.body %></p>
<hr>
<% end %>

app/views/posts/new.html.erb
<h1>Add New Post</h1>
<%= form_for :post, url: posts_path do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>